name: build
on:
  push:
    branches:
      - master

env:
  DOTNET_VERSION: '7.0.109'

jobs:
  build:
    permissions: write-all
    name: build-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: |
        dotnet publish --configuration Release --no-restore -o "aps_${{ matrix.os }}"
    - name: Zip output
      run: zip -qq -r aps_${{ matrix.os }}.zip aps_${{ matrix.os }}
    - name: Publish
      run: >-
        gh release create ${{ github.ref_name }}
        "aps_${{ matrix.os }}.zip"
        --generate-notes
        --title "Version ${{ github.ref_name }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}